### ISSUE TITLE
README and HTTPS status

### ISSUE THREAD

**Issue by marco-m** [taylorwood/lein-native-image#2]
Hello Taylor,

thanks for this plugin :-)

I was going through the README and saw the caveat

> HTTPS is currently unavailable but upcoming.

I had a look at the linked https://github.com/oracle/graal/issues/392, which has been closed as Done. It looks like that since native-image rc7 they support HTTPS (I haven't tried).

**Comment by taylorwood** [comment]
@marco-m Thanks for reporting! I made an example using HTTPS with macOS GraalVM CE 1.0.0-RC7 [here](https://github.com/taylorwood/clojurl#enable-graalvm-https-support), but forgot to update this README.
