### ISSUE TITLE
compiling a jdk 11 project

### ISSUE THREAD

**Issue by hoebat** [taylorwood/lein-native-image#4]
is there anyway to use native image on a jdk 11 project?

I'd like to be able to test java.net.http.httpclient on graal.

**Comment by taylorwood** [comment]
I don't think JDK 11 stuff is fully supported in Graal 19.2 but it sounds like they're working on it for 19.3. See discussion here for more https://github.com/oracle/graal/issues/651

**Comment by hoebat** [comment]
This is great news. Thanks!
