### ISSUE TITLE
advice for compiling using clojure 1.10

### ISSUE THREAD

**Issue by hoebat** [taylorwood/lein-native-image#5]
For me native image doesn't work for clojure 1.10 because of clojure.spec. Is there anyway around it or should I just stick to 1.9 for now?

**Comment by taylorwood** [comment]
There's a [known issue](https://dev.clojure.org/jira/browse/CLJ-1472) where usages of `clojure.core/locking` macro will fail native-image compilation. Clojure 1.10 depends on a version of clojure.spec that uses `locking`.
See [this commit](https://github.com/taylorwood/clojurl/commit/12b96b5e9a722b372f153436b1f6827709d0f2ab) for an example workaround.

**Comment by hoebat** [comment]
Thanks for that. Got it.
