### ISSUE TITLE
setting a flag in code when compiling

### ISSUE THREAD

**Issue by hoebat** [taylorwood/lein-native-image#6]
I'd like to set a var

```
(def ^:dynamic *native-compile* false)
```

to true when using the native image to compile the jar. Is this possible?

**Comment by taylorwood** [comment]
Yes, I think one way to do this would be via `:injections` in the `:native-image` profile:

https://github.com/technomancy/leiningen/blob/b6cf3392109f6d24277f2fd7d865f46a1cfdc47f/sample.project.clj#L182
